#cloud-config
%{ if length(ssh_authorized_keys) > 0 }
ssh_authorized_keys:
%{ for key in ssh_authorized_keys }
- ${key}
%{ endfor }
%{ endif }
write_files:
- path: /var/lib/rancher/k3s/server/manifests/aws-ccm.yaml
  encoding: gz+b64
  content: "${ccm}"
  owner: root:root
  permissions: '0644'
- path: /var/lib/rancher/k3s/server/manifests/aws-ebs.yaml
  encoding: gz+b64
  content: "${ebs}"
  owner: root:root
  permissions: '0644'
- path: /usr/local/bin/nodedrain.sh
  encoding: gz+b64
  content: "${nodedrain}"
  owner: root:root
  permissions: '0755'
- path: /etc/systemd/system/nodedrain.service
  encoding: gz+b64
  content: "${nodedrain_service}"
  owner: root:root
  permissions: '0644'
- path: /usr/local/bin/k3s.sh
  encoding: gz+b64
  content: "${k3s_install}"
  owner: root:root
  permissions: '0755'
%{ for manifest in manifests }
- path: /var/lib/rancher/k3s/server/manifests/${manifest.name}
  encoding: b64
  content: ${manifest.content}
  owner: ec2-user:ec2-user
  permissions: '0644'
%{ endfor }
