#cloud-config
%{ if length(ssh_authorized_keys) > 0 }
ssh_authorized_keys:
%{ for key in ssh_authorized_keys }
- ${key}
%{ endfor }
%{ endif }
write_files:
- path: /usr/local/bin/install.sh
  encoding: b64
  content: ${k3s_install}
  owner: ec2-user:ec2-user
  permissions: '0755'
%{~ for manifest in manifests }
- path: /var/lib/rancher/k3s/server/manifests/${manifest.name}
  encoding: b64
  content: ${manifest.content}
  owner: ec2-user:ec2-user
  permissions: '0644'
%{~ endfor }
